# Generated by Django 4.2.1 on 2023-05-18 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_worker_place_alter_worker_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='place',
            new_name='work',
        ),
    ]
