# Generated by Django 4.1.3 on 2023-05-20 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_rename_place_worker_work'),
    ]

    operations = [
        migrations.CreateModel(
            name='YourModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('description_1', models.TextField(blank=True)),
                ('email_1', models.CharField(max_length=255)),
            ],
        ),
    ]
