# Generated by Django 4.1.3 on 2023-05-20 02:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0004_yourmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='yourmodel',
            name='description_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='yourmodel',
            name='email_2',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
