# Generated by Django 4.1.3 on 2023-05-20 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0005_yourmodel_description_2_yourmodel_email_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yourmodel',
            name='description_2',
        ),
        migrations.RemoveField(
            model_name='yourmodel',
            name='email_2',
        ),
    ]
