# Generated by Django 4.1.3 on 2023-05-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0006_remove_yourmodel_description_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='yourmodel',
            name='description_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='yourmodel',
            name='email_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
