# Generated by Django 4.2.1 on 2023-05-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0007_yourmodel_description_2_yourmodel_email_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('pincode', models.CharField(max_length=10)),
                ('service', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='YourModel',
        ),
    ]
