# Generated by Django 4.2.1 on 2023-05-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0008_service_delete_yourmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='pincode',
        ),
        migrations.AddField(
            model_name='service',
            name='pin_codes',
            field=models.ManyToManyField(to='worker.pincode'),
        ),
    ]
