# Generated by Django 4.2.1 on 2023-05-23 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0012_customer_worker_mobile_no_customer_worker_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='worker_name',
            new_name='work_name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='worker_mobile_no',
            new_name='work_no',
        ),
    ]
