# Generated by Django 4.2.1 on 2023-06-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0017_remove_profile_uid_profile_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bookings',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='worker.customer'),
        ),
    ]
