# Generated by Django 4.2.1 on 2023-06-22 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0019_customer_approved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='work_no',
            new_name='worker_number',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='work_wo',
            new_name='worker_work',
        ),
    ]
